### PR TITLE
handle message with avro schema correctly

### LINKED ISSUE #128: [Bug] SQS Sink Connector should properly handle avro message
**Describe the bug**
If the topic with an avro schema, the connector fails to publish a message with the following error:
```
15:09:01.753 [SQSQueueBufferWorkerThread-10] ERROR org.apache.pulsar.ecosystem.io.sqs.SQSSink - failed send message to AWS SQS.
com.amazonaws.AmazonServiceException: Invalid binary character '#x2' was found in the message body, the set of allowed characters is #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]. (Service: AmazonSQS; Status Code: 0; Error Code: InvalidMessageContents; Request ID: null)
	at com.amazonaws.services.sqs.buffered.ResultConverter.convert(ResultConverter.java:37) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$SendMessageBatchTask.process(SendQueueBuffer.java:522) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$OutboundBatchTask.run(SendQueueBuffer.java:443) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. Create a topic with avro message
2. Run the sink connector

**Expected behavior**
The message should be converted to json format string and be published into sqs queue.

### PR DESCRIPTION
**Pull request by nlu90**
fix #128 

Published the avro message to sqs successfully:

image (15)

### CODE REVIEW

File: src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java [hunk 1]
```diff
@@ -73,6 +77,26 @@ public void onSuccess(SendMessageRequest request, SendMessageResult sendMessageR
...
     }
 
+    private String generateMessageBody(Record<GenericRecord> record) throws IOException {
+        if (record.getSchema() == null) {
+            return new String(record.getMessage().get().getData(), UTF_8);
+        } else {
+            SchemaInfo schemaInfo = record.getSchema().getSchemaInfo();
+            switch (schemaInfo.getType()) {
+                case AVRO:
+                    return handleAvroMessage(record.getValue(), schemaInfo.getSchemaDefinition());
```
Comment (sijie) [inline src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java:87]: I think you can just use [GenericRecord.getNativeObject()](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/GenericRecord.java#L87) to get the native object and use `Object.toString()` to convert it to a string.

**Review by freeznet — APPROVED** [review]
LGTM

**Review by tuteng — APPROVED** [review]
LGTM

File: src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java [hunk 2]
```diff
@@ -73,6 +76,20 @@ public void onSuccess(SendMessageRequest request, SendMessageResult sendMessageR
         });
     }
 
+    private String generateMessageBody(Record<GenericRecord> record) throws IOException {
+        if (record.getSchema() == null) {
+            return new String(record.getMessage().get().getData(), UTF_8);
+        } else {
+            SchemaInfo schemaInfo = record.getSchema().getSchemaInfo();
```
Comment (sijie) [inline src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java:83]: I think this can be simplified with the following logic.

```
if (record.getSchema() == null) {
    return new String(record.getMessage().get().getData(), UTF_8);
} else {
    Object nativeObject = record.getValue().getNativeObject();
    if (null == nativeObject) {
        return null;
    } else {
       return nativeObject.toString();
    }

}
```

File: src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java [hunk 3]
```diff
@@ -48,8 +50,8 @@ public void open(Map<String, Object> map, SinkContext sinkContext) throws Except
     }
 
     @Override
-    public void write(Record<byte[]> record) {
-        String msgBody = new String(record.getValue(), UTF_8);
+    public void write(Record<GenericRecord> record) throws IOException {
+        String msgBody = generateMessageBody(record);
```
Comment (sijie) [inline src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSSink.java:54]:
```suggestion
        String msgBody = generateMessageBody(record);
        if (msgBody == null) {
            record.ack();
            return;
        }
```

**Review by sijie — APPROVED** [review]
